---

- hosts: mysql
  user: vagrant
  become: yes
  become_method : sudo
  become_user: root
  vars:
    remote_user: root
    remote_user_passwd: root
  tasks:
    - name: install mariadb
      command: yum install -y mariadb-server

    - name: restart mysql
      command: systemctl restart mariadb

    - name: create remote user
      command: mysql -e "CREATE USER '{{remote_user}}'@'%' IDENTIFIED BY '{{remote_user_passwd}}';"

    - name: grant privillage
      command: mysql -e "GRANT all ON *.* TO '{{remote_user}}'@'%' IDENTIFIED by '{{remote_user_passwd}}';"

- hosts: all
  user: vagrant
  become: yes
  become_method : sudo
  become_user: root
  vars:
  tasks:
    - name: install mariadb client
      command: yum install -y mariadb-server
