# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  (1..4).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.box = "centos-7.3"
      node.vm.hostname="node#{i}"
      node.vm.network "private_network", ip: "192.168.59.1#{i}"
      node.vm.synced_folder "../share", "/home/vagrant/share"
      node.vm.provider "virtualbox" do |v|
        v.name = "node#{i}"
        v.memory = 3072
        v.cpus = 1
      end
      node.vm.provision "shell", inline: <<-SHELL
        sudo su -c "cat /home/vagrant/share/hosts >> /etc/hosts"
        sudo su -c "cat /home/vagrant/share/authorized_keys >> /home/vagrant/.ssh/authorized_keys"
      SHELL
    end
  end
end
