---

- hosts: livy
  user: vagrant
  become: yes
  become_method : sudo
  become_user: root
  vars:
    livy_version: 0.3.0
    livy_dir: /root/livy-{{livy_version}}
    livy_tarball_dir: /home/vagrant/share
    livy_log_dir: /data/livy/log

    spark_version: 2.1.0
    spark_dir: /root/spark-{{spark_version}}
  tasks:
    - name: "Ensure the livy dir exists at {{livy_dir}}"
      file: path={{livy_dir}} state=directory

    - name: install pip
      shell: pip install cloudpickle requests flake8 flaky pytest requests-kerberos configparser responses pytest_runner future

    #- name: get livy source code
    #  command: creates={{ livy_tarball_dir }}/livy-{{livy_version}}.tar.gz chdir={{ livy_tarball_dir }} curl -o https://github.com/cloudera/livy/archive/v0.3.0.tar.gz
    
    - name: Unpack tarball.
      command: tar zxf {{ livy_tarball_dir }}/livy-{{livy_version}}.tar.gz --strip-components=1  chdir={{ livy_dir }}

    - name: build livy
      shell: chdir={{ livy_dir }} mvn -Dmaven.test.skip clean package

    - name: "Ensure the livy_log_dir dir exists at {{livy_log_dir}}"
      file: path={{livy_log_dir}} state=directory

    - name: config livy
      template: src={{ item }} dest="{{livy_dir}}/conf/{{ item }}" owner=root group=root mode=0644
      with_items:
        - spark-blacklist.conf
        - livy-env.sh

    - name: stop livy
      command: nohup {{livy_dir}}/bin/livy-server stop &

    - name: start livy
      command: nohup {{livy_dir}}/bin/livy-server start &
