---

- hosts: all
  user: ubuntu
  become: yes
  become_method : sudo
  become_user: root
  vars:
  tasks:
    - name: Create ssh key 
      shell: echo y | ssh-keygen -t rsa -N '' -f /root/.ssh/id_rsa

    - name: Collect ssh keys
      shell: cat ~/.ssh/id_rsa.pub
      register: ssh_keys

    - name: check keys
      debug: msg="{{ ssh_keys.stdout }}"

    - name: deploy keys on all servers
      authorized_key: 
        user: root 
        key: "{{ item[0] }}"
      delegate_to: "{{ item[1] }}"
      with_nested:
        - "{{ ssh_keys.stdout }}"
        - "{{ groups['hadoop'] }}"

    - name: For each host, scan for its ssh public key
      command: "ssh-keyscan -t rsa {{ item }}"
      register: hosts
      with_items: "{{ groups['hadoop'] }}"

    - name: check hosts
      debug: msg="{{ hosts.results }}"

    - name: deploy hosts on all servers
      known_hosts:
        name: "{{ item.item }}"
        key: "{{ item.stdout }}"
        path: "/root/.ssh/known_hosts"
      with_items: '{{ hosts.results }}'
